### ISSUE TITLE
Gemcutter support

### ISSUE THREAD

**Issue by nesquena** [markevans/block_helpers#2]
Now that github stopped building gems, would be nice to see this on gemcutter.org

**Comment by markevans** [comment]
yeh - thanks I didn't realise github had stopped supporting gems.

I've pushed it to gemcutter - they don't do namespaces so it's just on there as block_helpers. Should probably add to rubyforge too really.

Cheers
Mark

**Comment by markevans** [comment]
meant to close!

**Comment by nesquena** [comment]
thanks mark. comes in handy as i move all my gem configs away from github :(
