### ISSUE TITLE
Inherting block helpers

### ISSUE THREAD

**Issue by lukemelia** [markevans/block_helpers#3]
Inheriting block helper classes almost works currently. However, if the subclass doesn't define the display method, it does not use the superclass' as I would expect.

**Comment by markevans** [comment]
I see what you mean.
Will think about the best way to get it to work (wouldn't be hard, but there are different ways of doing it)
In the mean time doing 

def display
  super

end

should work.

Out of interest, what kind of thing are you using inherited block helpers for?

**Comment by markevans** [comment]
Hi - this is fixed now - the subclass should correctly inherit the display method now (and can be overridden as would be expected).
The latest gem is now on gemcutter.org

**Comment by lukemelia** [comment]
Thanks for the fix, Mark. My use case was a content_box block partial that I had some extra logic in when I passed it a particular css class. It was hacky and crying out to be cleaned up, but it was mostly similar to the content_box instance.

I did the work in an experimental branch of our app, and I haven't yet decided whether to merge it in. While I like the idea of your plugin a lot, I haven't decided if I find the resulting code easy to work with or not.

**Comment by markevans** [comment]
yes - I've found that it's worth thinking about when to use it and when not to, as it's possible to overdo using it.

It certainly helps with a lot of cases, but with others it could potentially be more confusing I think.
I guess it just needs a judgement call for each case
